#! /bin/sh
$HOME/.config/polybar/launch.sh

pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Space between window and polybar
bspc config top_padding		22
# Space between window and bottom 
bspc config bottom_padding	0
# border color focus window
bspc config focused_border_color "#e0af68"
#normal
bspc config normal_border_color "#7aa2f7"

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a obs state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Gimp:gimp follow=on state=floating;
bspc rule -a Inkscape follow=on state=floating
bspc rule -a vlc state=floating
bspc rule -a TelegramDesktop:telegram-desktop state=floating
bspc rule -a Virt-manager state=floating
bspc rule -a Dbeaver state=floating
